// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactLabelInfoNotice.proto

package Jubo.JuLiao.IM.Wx.Proto;

public final class ContactLabelInfoNotice {
  private ContactLabelInfoNotice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LabelInfoMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 LabelId = 1;</code>
     */
    int getLabelId();

    /**
     * <code>string LabelName = 2;</code>
     */
    java.lang.String getLabelName();
    /**
     * <code>string LabelName = 2;</code>
     */
    com.google.protobuf.ByteString
        getLabelNameBytes();
  }
  /**
   * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage}
   */
  public  static final class LabelInfoMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage)
      LabelInfoMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LabelInfoMessage.newBuilder() to construct.
    private LabelInfoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LabelInfoMessage() {
      labelId_ = 0;
      labelName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LabelInfoMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              labelId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              labelName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_LabelInfoMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_LabelInfoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.class, Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.Builder.class);
    }

    public static final int LABELID_FIELD_NUMBER = 1;
    private int labelId_;
    /**
     * <code>int32 LabelId = 1;</code>
     */
    public int getLabelId() {
      return labelId_;
    }

    public static final int LABELNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object labelName_;
    /**
     * <code>string LabelName = 2;</code>
     */
    public java.lang.String getLabelName() {
      java.lang.Object ref = labelName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        labelName_ = s;
        return s;
      }
    }
    /**
     * <code>string LabelName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLabelNameBytes() {
      java.lang.Object ref = labelName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        labelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (labelId_ != 0) {
        output.writeInt32(1, labelId_);
      }
      if (!getLabelNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, labelName_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (labelId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, labelId_);
      }
      if (!getLabelNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, labelName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage)) {
        return super.equals(obj);
      }
      Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage other = (Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage) obj;

      boolean result = true;
      result = result && (getLabelId()
          == other.getLabelId());
      result = result && getLabelName()
          .equals(other.getLabelName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LABELID_FIELD_NUMBER;
      hash = (53 * hash) + getLabelId();
      hash = (37 * hash) + LABELNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLabelName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage)
        Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_LabelInfoMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_LabelInfoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.class, Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.Builder.class);
      }

      // Construct using Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        labelId_ = 0;

        labelName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_LabelInfoMessage_descriptor;
      }

      public Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage getDefaultInstanceForType() {
        return Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.getDefaultInstance();
      }

      public Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage build() {
        Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage buildPartial() {
        Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage result = new Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage(this);
        result.labelId_ = labelId_;
        result.labelName_ = labelName_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage) {
          return mergeFrom((Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage other) {
        if (other == Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.getDefaultInstance()) return this;
        if (other.getLabelId() != 0) {
          setLabelId(other.getLabelId());
        }
        if (!other.getLabelName().isEmpty()) {
          labelName_ = other.labelName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int labelId_ ;
      /**
       * <code>int32 LabelId = 1;</code>
       */
      public int getLabelId() {
        return labelId_;
      }
      /**
       * <code>int32 LabelId = 1;</code>
       */
      public Builder setLabelId(int value) {
        
        labelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 LabelId = 1;</code>
       */
      public Builder clearLabelId() {
        
        labelId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object labelName_ = "";
      /**
       * <code>string LabelName = 2;</code>
       */
      public java.lang.String getLabelName() {
        java.lang.Object ref = labelName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          labelName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string LabelName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLabelNameBytes() {
        java.lang.Object ref = labelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          labelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string LabelName = 2;</code>
       */
      public Builder setLabelName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        labelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string LabelName = 2;</code>
       */
      public Builder clearLabelName() {
        
        labelName_ = getDefaultInstance().getLabelName();
        onChanged();
        return this;
      }
      /**
       * <code>string LabelName = 2;</code>
       */
      public Builder setLabelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        labelName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage)
    }

    // @@protoc_insertion_point(class_scope:Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage)
    private static final Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage();
    }

    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LabelInfoMessage>
        PARSER = new com.google.protobuf.AbstractParser<LabelInfoMessage>() {
      public LabelInfoMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LabelInfoMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LabelInfoMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LabelInfoMessage> getParserForType() {
      return PARSER;
    }

    public Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContactLabelInfoNoticeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNoticeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 商家个人微信内部全局唯一识别码
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    java.lang.String getWeChatId();
    /**
     * <pre>
     * 商家个人微信内部全局唯一识别码
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    com.google.protobuf.ByteString
        getWeChatIdBytes();

    /**
     * <pre>
     * 标签列表
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
     */
    java.util.List<Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage> 
        getLabelsList();
    /**
     * <pre>
     * 标签列表
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
     */
    Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage getLabels(int index);
    /**
     * <pre>
     * 标签列表
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
     */
    int getLabelsCount();
    /**
     * <pre>
     * 标签列表
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
     */
    java.util.List<? extends Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessageOrBuilder> 
        getLabelsOrBuilderList();
    /**
     * <pre>
     * 标签列表
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
     */
    Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessageOrBuilder getLabelsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNoticeMessage}
   */
  public  static final class ContactLabelInfoNoticeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNoticeMessage)
      ContactLabelInfoNoticeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContactLabelInfoNoticeMessage.newBuilder() to construct.
    private ContactLabelInfoNoticeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContactLabelInfoNoticeMessage() {
      weChatId_ = "";
      labels_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContactLabelInfoNoticeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              weChatId_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                labels_ = new java.util.ArrayList<Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              labels_.add(
                  input.readMessage(Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          labels_ = java.util.Collections.unmodifiableList(labels_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_ContactLabelInfoNoticeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_ContactLabelInfoNoticeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage.class, Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage.Builder.class);
    }

    private int bitField0_;
    public static final int WECHATID_FIELD_NUMBER = 1;
    private volatile java.lang.Object weChatId_;
    /**
     * <pre>
     * 商家个人微信内部全局唯一识别码
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    public java.lang.String getWeChatId() {
      java.lang.Object ref = weChatId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weChatId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 商家个人微信内部全局唯一识别码
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWeChatIdBytes() {
      java.lang.Object ref = weChatId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weChatId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LABELS_FIELD_NUMBER = 2;
    private java.util.List<Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage> labels_;
    /**
     * <pre>
     * 标签列表
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
     */
    public java.util.List<Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage> getLabelsList() {
      return labels_;
    }
    /**
     * <pre>
     * 标签列表
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
     */
    public java.util.List<? extends Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessageOrBuilder> 
        getLabelsOrBuilderList() {
      return labels_;
    }
    /**
     * <pre>
     * 标签列表
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
     */
    public int getLabelsCount() {
      return labels_.size();
    }
    /**
     * <pre>
     * 标签列表
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
     */
    public Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage getLabels(int index) {
      return labels_.get(index);
    }
    /**
     * <pre>
     * 标签列表
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
     */
    public Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessageOrBuilder getLabelsOrBuilder(
        int index) {
      return labels_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWeChatIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, weChatId_);
      }
      for (int i = 0; i < labels_.size(); i++) {
        output.writeMessage(2, labels_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWeChatIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, weChatId_);
      }
      for (int i = 0; i < labels_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, labels_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage)) {
        return super.equals(obj);
      }
      Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage other = (Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage) obj;

      boolean result = true;
      result = result && getWeChatId()
          .equals(other.getWeChatId());
      result = result && getLabelsList()
          .equals(other.getLabelsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WECHATID_FIELD_NUMBER;
      hash = (53 * hash) + getWeChatId().hashCode();
      if (getLabelsCount() > 0) {
        hash = (37 * hash) + LABELS_FIELD_NUMBER;
        hash = (53 * hash) + getLabelsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNoticeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNoticeMessage)
        Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_ContactLabelInfoNoticeMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_ContactLabelInfoNoticeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage.class, Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage.Builder.class);
      }

      // Construct using Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLabelsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        weChatId_ = "";

        if (labelsBuilder_ == null) {
          labels_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          labelsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_ContactLabelInfoNoticeMessage_descriptor;
      }

      public Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage getDefaultInstanceForType() {
        return Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage.getDefaultInstance();
      }

      public Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage build() {
        Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage buildPartial() {
        Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage result = new Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.weChatId_ = weChatId_;
        if (labelsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            labels_ = java.util.Collections.unmodifiableList(labels_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.labels_ = labels_;
        } else {
          result.labels_ = labelsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage) {
          return mergeFrom((Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage other) {
        if (other == Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage.getDefaultInstance()) return this;
        if (!other.getWeChatId().isEmpty()) {
          weChatId_ = other.weChatId_;
          onChanged();
        }
        if (labelsBuilder_ == null) {
          if (!other.labels_.isEmpty()) {
            if (labels_.isEmpty()) {
              labels_ = other.labels_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureLabelsIsMutable();
              labels_.addAll(other.labels_);
            }
            onChanged();
          }
        } else {
          if (!other.labels_.isEmpty()) {
            if (labelsBuilder_.isEmpty()) {
              labelsBuilder_.dispose();
              labelsBuilder_ = null;
              labels_ = other.labels_;
              bitField0_ = (bitField0_ & ~0x00000002);
              labelsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLabelsFieldBuilder() : null;
            } else {
              labelsBuilder_.addAllMessages(other.labels_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object weChatId_ = "";
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public java.lang.String getWeChatId() {
        java.lang.Object ref = weChatId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          weChatId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWeChatIdBytes() {
        java.lang.Object ref = weChatId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          weChatId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder setWeChatId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        weChatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder clearWeChatId() {
        
        weChatId_ = getDefaultInstance().getWeChatId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder setWeChatIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        weChatId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage> labels_ =
        java.util.Collections.emptyList();
      private void ensureLabelsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          labels_ = new java.util.ArrayList<Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage>(labels_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage, Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.Builder, Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessageOrBuilder> labelsBuilder_;

      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public java.util.List<Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage> getLabelsList() {
        if (labelsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(labels_);
        } else {
          return labelsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public int getLabelsCount() {
        if (labelsBuilder_ == null) {
          return labels_.size();
        } else {
          return labelsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage getLabels(int index) {
        if (labelsBuilder_ == null) {
          return labels_.get(index);
        } else {
          return labelsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public Builder setLabels(
          int index, Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage value) {
        if (labelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabelsIsMutable();
          labels_.set(index, value);
          onChanged();
        } else {
          labelsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public Builder setLabels(
          int index, Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.Builder builderForValue) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          labels_.set(index, builderForValue.build());
          onChanged();
        } else {
          labelsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public Builder addLabels(Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage value) {
        if (labelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabelsIsMutable();
          labels_.add(value);
          onChanged();
        } else {
          labelsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public Builder addLabels(
          int index, Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage value) {
        if (labelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabelsIsMutable();
          labels_.add(index, value);
          onChanged();
        } else {
          labelsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public Builder addLabels(
          Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.Builder builderForValue) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          labels_.add(builderForValue.build());
          onChanged();
        } else {
          labelsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public Builder addLabels(
          int index, Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.Builder builderForValue) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          labels_.add(index, builderForValue.build());
          onChanged();
        } else {
          labelsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public Builder addAllLabels(
          java.lang.Iterable<? extends Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage> values) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, labels_);
          onChanged();
        } else {
          labelsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public Builder clearLabels() {
        if (labelsBuilder_ == null) {
          labels_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          labelsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public Builder removeLabels(int index) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          labels_.remove(index);
          onChanged();
        } else {
          labelsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.Builder getLabelsBuilder(
          int index) {
        return getLabelsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessageOrBuilder getLabelsOrBuilder(
          int index) {
        if (labelsBuilder_ == null) {
          return labels_.get(index);  } else {
          return labelsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public java.util.List<? extends Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessageOrBuilder> 
           getLabelsOrBuilderList() {
        if (labelsBuilder_ != null) {
          return labelsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(labels_);
        }
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.Builder addLabelsBuilder() {
        return getLabelsFieldBuilder().addBuilder(
            Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.getDefaultInstance());
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.Builder addLabelsBuilder(
          int index) {
        return getLabelsFieldBuilder().addBuilder(
            index, Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.getDefaultInstance());
      }
      /**
       * <pre>
       * 标签列表
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage Labels = 2;</code>
       */
      public java.util.List<Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.Builder> 
           getLabelsBuilderList() {
        return getLabelsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage, Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.Builder, Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessageOrBuilder> 
          getLabelsFieldBuilder() {
        if (labelsBuilder_ == null) {
          labelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage, Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessage.Builder, Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.LabelInfoMessageOrBuilder>(
                  labels_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          labels_ = null;
        }
        return labelsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNoticeMessage)
    }

    // @@protoc_insertion_point(class_scope:Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNoticeMessage)
    private static final Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage();
    }

    public static Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContactLabelInfoNoticeMessage>
        PARSER = new com.google.protobuf.AbstractParser<ContactLabelInfoNoticeMessage>() {
      public ContactLabelInfoNoticeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContactLabelInfoNoticeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContactLabelInfoNoticeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContactLabelInfoNoticeMessage> getParserForType() {
      return PARSER;
    }

    public Jubo.JuLiao.IM.Wx.Proto.ContactLabelInfoNotice.ContactLabelInfoNoticeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Jubo_JuLiao_IM_Wx_Proto_LabelInfoMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Jubo_JuLiao_IM_Wx_Proto_LabelInfoMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Jubo_JuLiao_IM_Wx_Proto_ContactLabelInfoNoticeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Jubo_JuLiao_IM_Wx_Proto_ContactLabelInfoNoticeMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034ContactLabelInfoNotice.proto\022\027Jubo.JuL" +
      "iao.IM.Wx.Proto\"6\n\020LabelInfoMessage\022\017\n\007L" +
      "abelId\030\001 \001(\005\022\021\n\tLabelName\030\002 \001(\t\"l\n\035Conta" +
      "ctLabelInfoNoticeMessage\022\020\n\010WeChatId\030\001 \001" +
      "(\t\0229\n\006Labels\030\002 \003(\0132).Jubo.JuLiao.IM.Wx.P" +
      "roto.LabelInfoMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_LabelInfoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_LabelInfoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Jubo_JuLiao_IM_Wx_Proto_LabelInfoMessage_descriptor,
        new java.lang.String[] { "LabelId", "LabelName", });
    internal_static_Jubo_JuLiao_IM_Wx_Proto_ContactLabelInfoNoticeMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_ContactLabelInfoNoticeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Jubo_JuLiao_IM_Wx_Proto_ContactLabelInfoNoticeMessage_descriptor,
        new java.lang.String[] { "WeChatId", "Labels", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
