// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceAuthReq.proto

package Jubo.JuLiao.IM.Wx.Proto;

public final class DeviceAuthReq {
  private DeviceAuthReq() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeviceAuthReqMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *认证方式
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
     */
    int getAuthTypeValue();
    /**
     * <pre>
     *认证方式
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
     */
    Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType getAuthType();

    /**
     * <pre>
     *凭证信息（不同认证方式传入不同的凭证信息）
     * </pre>
     *
     * <code>string Credential = 2;</code>
     */
    java.lang.String getCredential();
    /**
     * <pre>
     *凭证信息（不同认证方式传入不同的凭证信息）
     * </pre>
     *
     * <code>string Credential = 2;</code>
     */
    com.google.protobuf.ByteString
        getCredentialBytes();
  }
  /**
   * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage}
   */
  public  static final class DeviceAuthReqMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage)
      DeviceAuthReqMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeviceAuthReqMessage.newBuilder() to construct.
    private DeviceAuthReqMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeviceAuthReqMessage() {
      authType_ = 0;
      credential_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceAuthReqMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              authType_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              credential_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.internal_static_Jubo_JuLiao_IM_Wx_Proto_DeviceAuthReqMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.internal_static_Jubo_JuLiao_IM_Wx_Proto_DeviceAuthReqMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.class, Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.Builder.class);
    }

    /**
     * <pre>
     *认证方式枚举
     * </pre>
     *
     * Protobuf enum {@code Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage.EnumAuthType}
     */
    public enum EnumAuthType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *默认方式，默认使用
       * </pre>
       *
       * <code>Default = 0;</code>
       */
      Default(0),
      /**
       * <pre>
       *设备码（用于手机客户端，此方式Credential应传入手机IMEI）
       * </pre>
       *
       * <code>DeviceCode = 1;</code>
       */
      DeviceCode(1),
      /**
       * <pre>
       *用户名密码方式（此方式Credential应传入base64(user:pwd)）
       * </pre>
       *
       * <code>Username = 2;</code>
       */
      Username(2),
      /**
       * <pre>
       *内部服务间通讯方式（此方式Credential可为空，服务器根据ip白名单来认证）
       * </pre>
       *
       * <code>InternalCode = 3;</code>
       */
      InternalCode(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *默认方式，默认使用
       * </pre>
       *
       * <code>Default = 0;</code>
       */
      public static final int Default_VALUE = 0;
      /**
       * <pre>
       *设备码（用于手机客户端，此方式Credential应传入手机IMEI）
       * </pre>
       *
       * <code>DeviceCode = 1;</code>
       */
      public static final int DeviceCode_VALUE = 1;
      /**
       * <pre>
       *用户名密码方式（此方式Credential应传入base64(user:pwd)）
       * </pre>
       *
       * <code>Username = 2;</code>
       */
      public static final int Username_VALUE = 2;
      /**
       * <pre>
       *内部服务间通讯方式（此方式Credential可为空，服务器根据ip白名单来认证）
       * </pre>
       *
       * <code>InternalCode = 3;</code>
       */
      public static final int InternalCode_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EnumAuthType valueOf(int value) {
        return forNumber(value);
      }

      public static EnumAuthType forNumber(int value) {
        switch (value) {
          case 0: return Default;
          case 1: return DeviceCode;
          case 2: return Username;
          case 3: return InternalCode;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EnumAuthType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EnumAuthType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EnumAuthType>() {
              public EnumAuthType findValueByNumber(int number) {
                return EnumAuthType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final EnumAuthType[] VALUES = values();

      public static EnumAuthType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EnumAuthType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage.EnumAuthType)
    }

    public static final int AUTHTYPE_FIELD_NUMBER = 1;
    private int authType_;
    /**
     * <pre>
     *认证方式
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
     */
    public int getAuthTypeValue() {
      return authType_;
    }
    /**
     * <pre>
     *认证方式
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
     */
    public Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType getAuthType() {
      Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType result = Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType.valueOf(authType_);
      return result == null ? Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType.UNRECOGNIZED : result;
    }

    public static final int CREDENTIAL_FIELD_NUMBER = 2;
    private volatile java.lang.Object credential_;
    /**
     * <pre>
     *凭证信息（不同认证方式传入不同的凭证信息）
     * </pre>
     *
     * <code>string Credential = 2;</code>
     */
    public java.lang.String getCredential() {
      java.lang.Object ref = credential_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        credential_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *凭证信息（不同认证方式传入不同的凭证信息）
     * </pre>
     *
     * <code>string Credential = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCredentialBytes() {
      java.lang.Object ref = credential_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        credential_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (authType_ != Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType.Default.getNumber()) {
        output.writeEnum(1, authType_);
      }
      if (!getCredentialBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, credential_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (authType_ != Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType.Default.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, authType_);
      }
      if (!getCredentialBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, credential_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage)) {
        return super.equals(obj);
      }
      Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage other = (Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage) obj;

      boolean result = true;
      result = result && authType_ == other.authType_;
      result = result && getCredential()
          .equals(other.getCredential());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AUTHTYPE_FIELD_NUMBER;
      hash = (53 * hash) + authType_;
      hash = (37 * hash) + CREDENTIAL_FIELD_NUMBER;
      hash = (53 * hash) + getCredential().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage)
        Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.internal_static_Jubo_JuLiao_IM_Wx_Proto_DeviceAuthReqMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.internal_static_Jubo_JuLiao_IM_Wx_Proto_DeviceAuthReqMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.class, Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.Builder.class);
      }

      // Construct using Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        authType_ = 0;

        credential_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.internal_static_Jubo_JuLiao_IM_Wx_Proto_DeviceAuthReqMessage_descriptor;
      }

      public Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage getDefaultInstanceForType() {
        return Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.getDefaultInstance();
      }

      public Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage build() {
        Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage buildPartial() {
        Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage result = new Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage(this);
        result.authType_ = authType_;
        result.credential_ = credential_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage) {
          return mergeFrom((Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage other) {
        if (other == Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.getDefaultInstance()) return this;
        if (other.authType_ != 0) {
          setAuthTypeValue(other.getAuthTypeValue());
        }
        if (!other.getCredential().isEmpty()) {
          credential_ = other.credential_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int authType_ = 0;
      /**
       * <pre>
       *认证方式
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
       */
      public int getAuthTypeValue() {
        return authType_;
      }
      /**
       * <pre>
       *认证方式
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
       */
      public Builder setAuthTypeValue(int value) {
        authType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *认证方式
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType getAuthType() {
        Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType result = Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType.valueOf(authType_);
        return result == null ? Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *认证方式
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
       */
      public Builder setAuthType(Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        authType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *认证方式
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
       */
      public Builder clearAuthType() {
        
        authType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object credential_ = "";
      /**
       * <pre>
       *凭证信息（不同认证方式传入不同的凭证信息）
       * </pre>
       *
       * <code>string Credential = 2;</code>
       */
      public java.lang.String getCredential() {
        java.lang.Object ref = credential_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          credential_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *凭证信息（不同认证方式传入不同的凭证信息）
       * </pre>
       *
       * <code>string Credential = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCredentialBytes() {
        java.lang.Object ref = credential_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          credential_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *凭证信息（不同认证方式传入不同的凭证信息）
       * </pre>
       *
       * <code>string Credential = 2;</code>
       */
      public Builder setCredential(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        credential_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *凭证信息（不同认证方式传入不同的凭证信息）
       * </pre>
       *
       * <code>string Credential = 2;</code>
       */
      public Builder clearCredential() {
        
        credential_ = getDefaultInstance().getCredential();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *凭证信息（不同认证方式传入不同的凭证信息）
       * </pre>
       *
       * <code>string Credential = 2;</code>
       */
      public Builder setCredentialBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        credential_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage)
    }

    // @@protoc_insertion_point(class_scope:Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReqMessage)
    private static final Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage();
    }

    public static Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceAuthReqMessage>
        PARSER = new com.google.protobuf.AbstractParser<DeviceAuthReqMessage>() {
      public DeviceAuthReqMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceAuthReqMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeviceAuthReqMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceAuthReqMessage> getParserForType() {
      return PARSER;
    }

    public Jubo.JuLiao.IM.Wx.Proto.DeviceAuthReq.DeviceAuthReqMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Jubo_JuLiao_IM_Wx_Proto_DeviceAuthReqMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Jubo_JuLiao_IM_Wx_Proto_DeviceAuthReqMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023DeviceAuthReq.proto\022\027Jubo.JuLiao.IM.Wx" +
      ".Proto\"\305\001\n\024DeviceAuthReqMessage\022L\n\010AuthT" +
      "ype\030\001 \001(\0162:.Jubo.JuLiao.IM.Wx.Proto.Devi" +
      "ceAuthReqMessage.EnumAuthType\022\022\n\nCredent" +
      "ial\030\002 \001(\t\"K\n\014EnumAuthType\022\013\n\007Default\020\000\022\016" +
      "\n\nDeviceCode\020\001\022\014\n\010Username\020\002\022\020\n\014Internal" +
      "Code\020\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_DeviceAuthReqMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_DeviceAuthReqMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Jubo_JuLiao_IM_Wx_Proto_DeviceAuthReqMessage_descriptor,
        new java.lang.String[] { "AuthType", "Credential", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
