// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ForwardMessageByContentTask.proto

package Jubo.JuLiao.IM.Wx.Proto;

public final class ForwardMessageByContentTask {
  private ForwardMessageByContentTask() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ForwardMessageByContentTaskMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTaskMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    java.lang.String getWeChatId();
    /**
     * <pre>
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    com.google.protobuf.ByteString
        getWeChatIdBytes();

    /**
     * <pre>
     *目标人群id列表，用分号;分隔
     * </pre>
     *
     * <code>string FriendIds = 2;</code>
     */
    java.lang.String getFriendIds();
    /**
     * <pre>
     *目标人群id列表，用分号;分隔
     * </pre>
     *
     * <code>string FriendIds = 2;</code>
     */
    com.google.protobuf.ByteString
        getFriendIdsBytes();

    /**
     * <pre>
     * 消息Id, 非必须
     * </pre>
     *
     * <code>int64 MsgSrvId = 3;</code>
     */
    long getMsgSrvId();

    /**
     * <pre>
     * 消息的原始类型，一般为49，链接消息
     * </pre>
     *
     * <code>int32 MsgType = 4;</code>
     */
    int getMsgType();

    /**
     * <pre>
     * 消息的原始内容
     * </pre>
     *
     * <code>string Content = 5;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 消息的原始内容
     * </pre>
     *
     * <code>string Content = 5;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>int64 TaskId = 6;</code>
     */
    long getTaskId();
  }
  /**
   * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTaskMessage}
   */
  public  static final class ForwardMessageByContentTaskMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTaskMessage)
      ForwardMessageByContentTaskMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ForwardMessageByContentTaskMessage.newBuilder() to construct.
    private ForwardMessageByContentTaskMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ForwardMessageByContentTaskMessage() {
      weChatId_ = "";
      friendIds_ = "";
      msgSrvId_ = 0L;
      msgType_ = 0;
      content_ = "";
      taskId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ForwardMessageByContentTaskMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              weChatId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              friendIds_ = s;
              break;
            }
            case 24: {

              msgSrvId_ = input.readInt64();
              break;
            }
            case 32: {

              msgType_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 48: {

              taskId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.internal_static_Jubo_JuLiao_IM_Wx_Proto_ForwardMessageByContentTaskMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.internal_static_Jubo_JuLiao_IM_Wx_Proto_ForwardMessageByContentTaskMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage.class, Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage.Builder.class);
    }

    public static final int WECHATID_FIELD_NUMBER = 1;
    private volatile java.lang.Object weChatId_;
    /**
     * <pre>
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    public java.lang.String getWeChatId() {
      java.lang.Object ref = weChatId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weChatId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWeChatIdBytes() {
      java.lang.Object ref = weChatId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weChatId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FRIENDIDS_FIELD_NUMBER = 2;
    private volatile java.lang.Object friendIds_;
    /**
     * <pre>
     *目标人群id列表，用分号;分隔
     * </pre>
     *
     * <code>string FriendIds = 2;</code>
     */
    public java.lang.String getFriendIds() {
      java.lang.Object ref = friendIds_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        friendIds_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *目标人群id列表，用分号;分隔
     * </pre>
     *
     * <code>string FriendIds = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFriendIdsBytes() {
      java.lang.Object ref = friendIds_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        friendIds_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGSRVID_FIELD_NUMBER = 3;
    private long msgSrvId_;
    /**
     * <pre>
     * 消息Id, 非必须
     * </pre>
     *
     * <code>int64 MsgSrvId = 3;</code>
     */
    public long getMsgSrvId() {
      return msgSrvId_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 4;
    private int msgType_;
    /**
     * <pre>
     * 消息的原始类型，一般为49，链接消息
     * </pre>
     *
     * <code>int32 MsgType = 4;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int CONTENT_FIELD_NUMBER = 5;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     * 消息的原始内容
     * </pre>
     *
     * <code>string Content = 5;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息的原始内容
     * </pre>
     *
     * <code>string Content = 5;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKID_FIELD_NUMBER = 6;
    private long taskId_;
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 TaskId = 6;</code>
     */
    public long getTaskId() {
      return taskId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWeChatIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, weChatId_);
      }
      if (!getFriendIdsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, friendIds_);
      }
      if (msgSrvId_ != 0L) {
        output.writeInt64(3, msgSrvId_);
      }
      if (msgType_ != 0) {
        output.writeInt32(4, msgType_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, content_);
      }
      if (taskId_ != 0L) {
        output.writeInt64(6, taskId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWeChatIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, weChatId_);
      }
      if (!getFriendIdsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, friendIds_);
      }
      if (msgSrvId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, msgSrvId_);
      }
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, msgType_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, content_);
      }
      if (taskId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, taskId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage)) {
        return super.equals(obj);
      }
      Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage other = (Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage) obj;

      boolean result = true;
      result = result && getWeChatId()
          .equals(other.getWeChatId());
      result = result && getFriendIds()
          .equals(other.getFriendIds());
      result = result && (getMsgSrvId()
          == other.getMsgSrvId());
      result = result && (getMsgType()
          == other.getMsgType());
      result = result && getContent()
          .equals(other.getContent());
      result = result && (getTaskId()
          == other.getTaskId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WECHATID_FIELD_NUMBER;
      hash = (53 * hash) + getWeChatId().hashCode();
      hash = (37 * hash) + FRIENDIDS_FIELD_NUMBER;
      hash = (53 * hash) + getFriendIds().hashCode();
      hash = (37 * hash) + MSGSRVID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgSrvId());
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTaskId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTaskMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTaskMessage)
        Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.internal_static_Jubo_JuLiao_IM_Wx_Proto_ForwardMessageByContentTaskMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.internal_static_Jubo_JuLiao_IM_Wx_Proto_ForwardMessageByContentTaskMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage.class, Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage.Builder.class);
      }

      // Construct using Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        weChatId_ = "";

        friendIds_ = "";

        msgSrvId_ = 0L;

        msgType_ = 0;

        content_ = "";

        taskId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.internal_static_Jubo_JuLiao_IM_Wx_Proto_ForwardMessageByContentTaskMessage_descriptor;
      }

      public Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage getDefaultInstanceForType() {
        return Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage.getDefaultInstance();
      }

      public Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage build() {
        Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage buildPartial() {
        Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage result = new Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage(this);
        result.weChatId_ = weChatId_;
        result.friendIds_ = friendIds_;
        result.msgSrvId_ = msgSrvId_;
        result.msgType_ = msgType_;
        result.content_ = content_;
        result.taskId_ = taskId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage) {
          return mergeFrom((Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage other) {
        if (other == Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage.getDefaultInstance()) return this;
        if (!other.getWeChatId().isEmpty()) {
          weChatId_ = other.weChatId_;
          onChanged();
        }
        if (!other.getFriendIds().isEmpty()) {
          friendIds_ = other.friendIds_;
          onChanged();
        }
        if (other.getMsgSrvId() != 0L) {
          setMsgSrvId(other.getMsgSrvId());
        }
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getTaskId() != 0L) {
          setTaskId(other.getTaskId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object weChatId_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public java.lang.String getWeChatId() {
        java.lang.Object ref = weChatId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          weChatId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWeChatIdBytes() {
        java.lang.Object ref = weChatId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          weChatId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder setWeChatId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        weChatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder clearWeChatId() {
        
        weChatId_ = getDefaultInstance().getWeChatId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder setWeChatIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        weChatId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object friendIds_ = "";
      /**
       * <pre>
       *目标人群id列表，用分号;分隔
       * </pre>
       *
       * <code>string FriendIds = 2;</code>
       */
      public java.lang.String getFriendIds() {
        java.lang.Object ref = friendIds_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          friendIds_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *目标人群id列表，用分号;分隔
       * </pre>
       *
       * <code>string FriendIds = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFriendIdsBytes() {
        java.lang.Object ref = friendIds_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          friendIds_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *目标人群id列表，用分号;分隔
       * </pre>
       *
       * <code>string FriendIds = 2;</code>
       */
      public Builder setFriendIds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        friendIds_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标人群id列表，用分号;分隔
       * </pre>
       *
       * <code>string FriendIds = 2;</code>
       */
      public Builder clearFriendIds() {
        
        friendIds_ = getDefaultInstance().getFriendIds();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标人群id列表，用分号;分隔
       * </pre>
       *
       * <code>string FriendIds = 2;</code>
       */
      public Builder setFriendIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        friendIds_ = value;
        onChanged();
        return this;
      }

      private long msgSrvId_ ;
      /**
       * <pre>
       * 消息Id, 非必须
       * </pre>
       *
       * <code>int64 MsgSrvId = 3;</code>
       */
      public long getMsgSrvId() {
        return msgSrvId_;
      }
      /**
       * <pre>
       * 消息Id, 非必须
       * </pre>
       *
       * <code>int64 MsgSrvId = 3;</code>
       */
      public Builder setMsgSrvId(long value) {
        
        msgSrvId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息Id, 非必须
       * </pre>
       *
       * <code>int64 MsgSrvId = 3;</code>
       */
      public Builder clearMsgSrvId() {
        
        msgSrvId_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <pre>
       * 消息的原始类型，一般为49，链接消息
       * </pre>
       *
       * <code>int32 MsgType = 4;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <pre>
       * 消息的原始类型，一般为49，链接消息
       * </pre>
       *
       * <code>int32 MsgType = 4;</code>
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息的原始类型，一般为49，链接消息
       * </pre>
       *
       * <code>int32 MsgType = 4;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 消息的原始内容
       * </pre>
       *
       * <code>string Content = 5;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 消息的原始内容
       * </pre>
       *
       * <code>string Content = 5;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息的原始内容
       * </pre>
       *
       * <code>string Content = 5;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息的原始内容
       * </pre>
       *
       * <code>string Content = 5;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息的原始内容
       * </pre>
       *
       * <code>string Content = 5;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private long taskId_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 TaskId = 6;</code>
       */
      public long getTaskId() {
        return taskId_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 TaskId = 6;</code>
       */
      public Builder setTaskId(long value) {
        
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 TaskId = 6;</code>
       */
      public Builder clearTaskId() {
        
        taskId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTaskMessage)
    }

    // @@protoc_insertion_point(class_scope:Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTaskMessage)
    private static final Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage();
    }

    public static Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ForwardMessageByContentTaskMessage>
        PARSER = new com.google.protobuf.AbstractParser<ForwardMessageByContentTaskMessage>() {
      public ForwardMessageByContentTaskMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ForwardMessageByContentTaskMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ForwardMessageByContentTaskMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ForwardMessageByContentTaskMessage> getParserForType() {
      return PARSER;
    }

    public Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTask.ForwardMessageByContentTaskMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Jubo_JuLiao_IM_Wx_Proto_ForwardMessageByContentTaskMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Jubo_JuLiao_IM_Wx_Proto_ForwardMessageByContentTaskMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!ForwardMessageByContentTask.proto\022\027Jub" +
      "o.JuLiao.IM.Wx.Proto\"\215\001\n\"ForwardMessageB" +
      "yContentTaskMessage\022\020\n\010WeChatId\030\001 \001(\t\022\021\n" +
      "\tFriendIds\030\002 \001(\t\022\020\n\010MsgSrvId\030\003 \001(\003\022\017\n\007Ms" +
      "gType\030\004 \001(\005\022\017\n\007Content\030\005 \001(\t\022\016\n\006TaskId\030\006" +
      " \001(\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_ForwardMessageByContentTaskMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_ForwardMessageByContentTaskMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Jubo_JuLiao_IM_Wx_Proto_ForwardMessageByContentTaskMessage_descriptor,
        new java.lang.String[] { "WeChatId", "FriendIds", "MsgSrvId", "MsgType", "Content", "TaskId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
