// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FriendTalkNotice.proto

package Jubo.JuLiao.IM.Wx.Proto;

public final class FriendTalkNotice {
  private FriendTalkNotice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FriendTalkNoticeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Jubo.JuLiao.IM.Wx.Proto.FriendTalkNoticeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 商家个人微信内部全局唯一识别码
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    java.lang.String getWeChatId();
    /**
     * <pre>
     * 商家个人微信内部全局唯一识别码
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    com.google.protobuf.ByteString
        getWeChatIdBytes();

    /**
     * <pre>
     * 好友微信内部全局唯一识别码
     * </pre>
     *
     * <code>string FriendId = 3;</code>
     */
    java.lang.String getFriendId();
    /**
     * <pre>
     * 好友微信内部全局唯一识别码
     * </pre>
     *
     * <code>string FriendId = 3;</code>
     */
    com.google.protobuf.ByteString
        getFriendIdBytes();

    /**
     * <pre>
     * 发送的消息内容类型
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 5;</code>
     */
    int getContentTypeValue();
    /**
     * <pre>
     * 发送的消息内容类型
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 5;</code>
     */
    Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumContentType getContentType();

    /**
     * <pre>
     * 内容 二进制流
     * </pre>
     *
     * <code>bytes Content = 6;</code>
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <pre>
     *服务端的主键id
     * </pre>
     *
     * <code>int64 MsgId = 7;</code>
     */
    long getMsgId();

    /**
     * <pre>
     * 消息唯一id
     * </pre>
     *
     * <code>int64 msgSvrId = 8;</code>
     */
    long getMsgSvrId();
  }
  /**
   * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.FriendTalkNoticeMessage}
   */
  public  static final class FriendTalkNoticeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Jubo.JuLiao.IM.Wx.Proto.FriendTalkNoticeMessage)
      FriendTalkNoticeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FriendTalkNoticeMessage.newBuilder() to construct.
    private FriendTalkNoticeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FriendTalkNoticeMessage() {
      weChatId_ = "";
      friendId_ = "";
      contentType_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
      msgId_ = 0L;
      msgSvrId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FriendTalkNoticeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              weChatId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              friendId_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              contentType_ = rawValue;
              break;
            }
            case 50: {

              content_ = input.readBytes();
              break;
            }
            case 56: {

              msgId_ = input.readInt64();
              break;
            }
            case 64: {

              msgSvrId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_FriendTalkNoticeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_FriendTalkNoticeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage.class, Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage.Builder.class);
    }

    public static final int WECHATID_FIELD_NUMBER = 1;
    private volatile java.lang.Object weChatId_;
    /**
     * <pre>
     * 商家个人微信内部全局唯一识别码
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    public java.lang.String getWeChatId() {
      java.lang.Object ref = weChatId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weChatId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 商家个人微信内部全局唯一识别码
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWeChatIdBytes() {
      java.lang.Object ref = weChatId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weChatId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FRIENDID_FIELD_NUMBER = 3;
    private volatile java.lang.Object friendId_;
    /**
     * <pre>
     * 好友微信内部全局唯一识别码
     * </pre>
     *
     * <code>string FriendId = 3;</code>
     */
    public java.lang.String getFriendId() {
      java.lang.Object ref = friendId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        friendId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 好友微信内部全局唯一识别码
     * </pre>
     *
     * <code>string FriendId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFriendIdBytes() {
      java.lang.Object ref = friendId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        friendId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTTYPE_FIELD_NUMBER = 5;
    private int contentType_;
    /**
     * <pre>
     * 发送的消息内容类型
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 5;</code>
     */
    public int getContentTypeValue() {
      return contentType_;
    }
    /**
     * <pre>
     * 发送的消息内容类型
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 5;</code>
     */
    public Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumContentType getContentType() {
      Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumContentType result = Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumContentType.valueOf(contentType_);
      return result == null ? Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumContentType.UNRECOGNIZED : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString content_;
    /**
     * <pre>
     * 内容 二进制流
     * </pre>
     *
     * <code>bytes Content = 6;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int MSGID_FIELD_NUMBER = 7;
    private long msgId_;
    /**
     * <pre>
     *服务端的主键id
     * </pre>
     *
     * <code>int64 MsgId = 7;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    public static final int MSGSVRID_FIELD_NUMBER = 8;
    private long msgSvrId_;
    /**
     * <pre>
     * 消息唯一id
     * </pre>
     *
     * <code>int64 msgSvrId = 8;</code>
     */
    public long getMsgSvrId() {
      return msgSvrId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWeChatIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, weChatId_);
      }
      if (!getFriendIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, friendId_);
      }
      if (contentType_ != Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumContentType.UnknownContent.getNumber()) {
        output.writeEnum(5, contentType_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(6, content_);
      }
      if (msgId_ != 0L) {
        output.writeInt64(7, msgId_);
      }
      if (msgSvrId_ != 0L) {
        output.writeInt64(8, msgSvrId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWeChatIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, weChatId_);
      }
      if (!getFriendIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, friendId_);
      }
      if (contentType_ != Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumContentType.UnknownContent.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, contentType_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, content_);
      }
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, msgId_);
      }
      if (msgSvrId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, msgSvrId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage)) {
        return super.equals(obj);
      }
      Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage other = (Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage) obj;

      boolean result = true;
      result = result && getWeChatId()
          .equals(other.getWeChatId());
      result = result && getFriendId()
          .equals(other.getFriendId());
      result = result && contentType_ == other.contentType_;
      result = result && getContent()
          .equals(other.getContent());
      result = result && (getMsgId()
          == other.getMsgId());
      result = result && (getMsgSvrId()
          == other.getMsgSvrId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WECHATID_FIELD_NUMBER;
      hash = (53 * hash) + getWeChatId().hashCode();
      hash = (37 * hash) + FRIENDID_FIELD_NUMBER;
      hash = (53 * hash) + getFriendId().hashCode();
      hash = (37 * hash) + CONTENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + contentType_;
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (37 * hash) + MSGSVRID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgSvrId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.FriendTalkNoticeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Jubo.JuLiao.IM.Wx.Proto.FriendTalkNoticeMessage)
        Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_FriendTalkNoticeMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_FriendTalkNoticeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage.class, Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage.Builder.class);
      }

      // Construct using Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        weChatId_ = "";

        friendId_ = "";

        contentType_ = 0;

        content_ = com.google.protobuf.ByteString.EMPTY;

        msgId_ = 0L;

        msgSvrId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_FriendTalkNoticeMessage_descriptor;
      }

      public Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage getDefaultInstanceForType() {
        return Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage.getDefaultInstance();
      }

      public Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage build() {
        Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage buildPartial() {
        Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage result = new Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage(this);
        result.weChatId_ = weChatId_;
        result.friendId_ = friendId_;
        result.contentType_ = contentType_;
        result.content_ = content_;
        result.msgId_ = msgId_;
        result.msgSvrId_ = msgSvrId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage) {
          return mergeFrom((Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage other) {
        if (other == Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage.getDefaultInstance()) return this;
        if (!other.getWeChatId().isEmpty()) {
          weChatId_ = other.weChatId_;
          onChanged();
        }
        if (!other.getFriendId().isEmpty()) {
          friendId_ = other.friendId_;
          onChanged();
        }
        if (other.contentType_ != 0) {
          setContentTypeValue(other.getContentTypeValue());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        if (other.getMsgSvrId() != 0L) {
          setMsgSvrId(other.getMsgSvrId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object weChatId_ = "";
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public java.lang.String getWeChatId() {
        java.lang.Object ref = weChatId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          weChatId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWeChatIdBytes() {
        java.lang.Object ref = weChatId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          weChatId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder setWeChatId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        weChatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder clearWeChatId() {
        
        weChatId_ = getDefaultInstance().getWeChatId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder setWeChatIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        weChatId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object friendId_ = "";
      /**
       * <pre>
       * 好友微信内部全局唯一识别码
       * </pre>
       *
       * <code>string FriendId = 3;</code>
       */
      public java.lang.String getFriendId() {
        java.lang.Object ref = friendId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          friendId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 好友微信内部全局唯一识别码
       * </pre>
       *
       * <code>string FriendId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFriendIdBytes() {
        java.lang.Object ref = friendId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          friendId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 好友微信内部全局唯一识别码
       * </pre>
       *
       * <code>string FriendId = 3;</code>
       */
      public Builder setFriendId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        friendId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 好友微信内部全局唯一识别码
       * </pre>
       *
       * <code>string FriendId = 3;</code>
       */
      public Builder clearFriendId() {
        
        friendId_ = getDefaultInstance().getFriendId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 好友微信内部全局唯一识别码
       * </pre>
       *
       * <code>string FriendId = 3;</code>
       */
      public Builder setFriendIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        friendId_ = value;
        onChanged();
        return this;
      }

      private int contentType_ = 0;
      /**
       * <pre>
       * 发送的消息内容类型
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 5;</code>
       */
      public int getContentTypeValue() {
        return contentType_;
      }
      /**
       * <pre>
       * 发送的消息内容类型
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 5;</code>
       */
      public Builder setContentTypeValue(int value) {
        contentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送的消息内容类型
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 5;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumContentType getContentType() {
        Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumContentType result = Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumContentType.valueOf(contentType_);
        return result == null ? Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumContentType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 发送的消息内容类型
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 5;</code>
       */
      public Builder setContentType(Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumContentType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        contentType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送的消息内容类型
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 5;</code>
       */
      public Builder clearContentType() {
        
        contentType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 内容 二进制流
       * </pre>
       *
       * <code>bytes Content = 6;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <pre>
       * 内容 二进制流
       * </pre>
       *
       * <code>bytes Content = 6;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容 二进制流
       * </pre>
       *
       * <code>bytes Content = 6;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private long msgId_ ;
      /**
       * <pre>
       *服务端的主键id
       * </pre>
       *
       * <code>int64 MsgId = 7;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *服务端的主键id
       * </pre>
       *
       * <code>int64 MsgId = 7;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务端的主键id
       * </pre>
       *
       * <code>int64 MsgId = 7;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private long msgSvrId_ ;
      /**
       * <pre>
       * 消息唯一id
       * </pre>
       *
       * <code>int64 msgSvrId = 8;</code>
       */
      public long getMsgSvrId() {
        return msgSvrId_;
      }
      /**
       * <pre>
       * 消息唯一id
       * </pre>
       *
       * <code>int64 msgSvrId = 8;</code>
       */
      public Builder setMsgSvrId(long value) {
        
        msgSvrId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息唯一id
       * </pre>
       *
       * <code>int64 msgSvrId = 8;</code>
       */
      public Builder clearMsgSvrId() {
        
        msgSvrId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Jubo.JuLiao.IM.Wx.Proto.FriendTalkNoticeMessage)
    }

    // @@protoc_insertion_point(class_scope:Jubo.JuLiao.IM.Wx.Proto.FriendTalkNoticeMessage)
    private static final Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage();
    }

    public static Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FriendTalkNoticeMessage>
        PARSER = new com.google.protobuf.AbstractParser<FriendTalkNoticeMessage>() {
      public FriendTalkNoticeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FriendTalkNoticeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FriendTalkNoticeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FriendTalkNoticeMessage> getParserForType() {
      return PARSER;
    }

    public Jubo.JuLiao.IM.Wx.Proto.FriendTalkNotice.FriendTalkNoticeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Jubo_JuLiao_IM_Wx_Proto_FriendTalkNoticeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Jubo_JuLiao_IM_Wx_Proto_FriendTalkNoticeMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026FriendTalkNotice.proto\022\027Jubo.JuLiao.IM" +
      ".Wx.Proto\032\026TransportMessage.proto\"\256\001\n\027Fr" +
      "iendTalkNoticeMessage\022\020\n\010WeChatId\030\001 \001(\t\022" +
      "\020\n\010FriendId\030\003 \001(\t\022=\n\013ContentType\030\005 \001(\0162(" +
      ".Jubo.JuLiao.IM.Wx.Proto.EnumContentType" +
      "\022\017\n\007Content\030\006 \001(\014\022\r\n\005MsgId\030\007 \001(\003\022\020\n\010msgS" +
      "vrId\030\010 \001(\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_FriendTalkNoticeMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_FriendTalkNoticeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Jubo_JuLiao_IM_Wx_Proto_FriendTalkNoticeMessage_descriptor,
        new java.lang.String[] { "WeChatId", "FriendId", "ContentType", "Content", "MsgId", "MsgSvrId", });
    Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
