// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostDeviceInfoNotice.proto

package Jubo.JuLiao.IM.Wx.Proto;

public final class PostDeviceInfoNotice {
  private PostDeviceInfoNotice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PostDeviceInfoNoticeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 手机品牌
     * </pre>
     *
     * <code>string PhoneBrand = 1;</code>
     */
    java.lang.String getPhoneBrand();
    /**
     * <pre>
     * 手机品牌
     * </pre>
     *
     * <code>string PhoneBrand = 1;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBrandBytes();

    /**
     * <pre>
     * 手机型号
     * </pre>
     *
     * <code>string PhoneModel = 2;</code>
     */
    java.lang.String getPhoneModel();
    /**
     * <pre>
     * 手机型号
     * </pre>
     *
     * <code>string PhoneModel = 2;</code>
     */
    com.google.protobuf.ByteString
        getPhoneModelBytes();

    /**
     * <code>int32 OSVerNumber = 3;</code>
     */
    int getOSVerNumber();

    /**
     * <pre>
     * App信息
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
     */
    java.util.List<Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage> 
        getAppInfosList();
    /**
     * <pre>
     * App信息
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
     */
    Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage getAppInfos(int index);
    /**
     * <pre>
     * App信息
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
     */
    int getAppInfosCount();
    /**
     * <pre>
     * App信息
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
     */
    java.util.List<? extends Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessageOrBuilder> 
        getAppInfosOrBuilderList();
    /**
     * <pre>
     * App信息
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
     */
    Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessageOrBuilder getAppInfosOrBuilder(
        int index);

    /**
     * <code>string NetType = 5;</code>
     */
    java.lang.String getNetType();
    /**
     * <code>string NetType = 5;</code>
     */
    com.google.protobuf.ByteString
        getNetTypeBytes();
  }
  /**
   * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage}
   */
  public  static final class PostDeviceInfoNoticeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage)
      PostDeviceInfoNoticeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PostDeviceInfoNoticeMessage.newBuilder() to construct.
    private PostDeviceInfoNoticeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PostDeviceInfoNoticeMessage() {
      phoneBrand_ = "";
      phoneModel_ = "";
      oSVerNumber_ = 0;
      appInfos_ = java.util.Collections.emptyList();
      netType_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PostDeviceInfoNoticeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              phoneBrand_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              phoneModel_ = s;
              break;
            }
            case 24: {

              oSVerNumber_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                appInfos_ = new java.util.ArrayList<Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage>();
                mutable_bitField0_ |= 0x00000008;
              }
              appInfos_.add(
                  input.readMessage(Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.parser(), extensionRegistry));
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              netType_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          appInfos_ = java.util.Collections.unmodifiableList(appInfos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.class, Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.Builder.class);
    }

    public interface DeviceAppInfoMessageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string PackageName = 1;</code>
       */
      java.lang.String getPackageName();
      /**
       * <code>string PackageName = 1;</code>
       */
      com.google.protobuf.ByteString
          getPackageNameBytes();

      /**
       * <code>string AppName = 2;</code>
       */
      java.lang.String getAppName();
      /**
       * <code>string AppName = 2;</code>
       */
      com.google.protobuf.ByteString
          getAppNameBytes();

      /**
       * <code>int32 VerNumber = 3;</code>
       */
      int getVerNumber();

      /**
       * <code>string Version = 4;</code>
       */
      java.lang.String getVersion();
      /**
       * <code>string Version = 4;</code>
       */
      com.google.protobuf.ByteString
          getVersionBytes();
    }
    /**
     * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage}
     */
    public  static final class DeviceAppInfoMessage extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage)
        DeviceAppInfoMessageOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use DeviceAppInfoMessage.newBuilder() to construct.
      private DeviceAppInfoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private DeviceAppInfoMessage() {
        packageName_ = "";
        appName_ = "";
        verNumber_ = 0;
        version_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private DeviceAppInfoMessage(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                packageName_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                appName_ = s;
                break;
              }
              case 24: {

                verNumber_ = input.readInt32();
                break;
              }
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();

                version_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_DeviceAppInfoMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_DeviceAppInfoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.class, Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.Builder.class);
      }

      public static final int PACKAGENAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object packageName_;
      /**
       * <code>string PackageName = 1;</code>
       */
      public java.lang.String getPackageName() {
        java.lang.Object ref = packageName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          packageName_ = s;
          return s;
        }
      }
      /**
       * <code>string PackageName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPackageNameBytes() {
        java.lang.Object ref = packageName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          packageName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int APPNAME_FIELD_NUMBER = 2;
      private volatile java.lang.Object appName_;
      /**
       * <code>string AppName = 2;</code>
       */
      public java.lang.String getAppName() {
        java.lang.Object ref = appName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appName_ = s;
          return s;
        }
      }
      /**
       * <code>string AppName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppNameBytes() {
        java.lang.Object ref = appName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VERNUMBER_FIELD_NUMBER = 3;
      private int verNumber_;
      /**
       * <code>int32 VerNumber = 3;</code>
       */
      public int getVerNumber() {
        return verNumber_;
      }

      public static final int VERSION_FIELD_NUMBER = 4;
      private volatile java.lang.Object version_;
      /**
       * <code>string Version = 4;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        }
      }
      /**
       * <code>string Version = 4;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getPackageNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, packageName_);
        }
        if (!getAppNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appName_);
        }
        if (verNumber_ != 0) {
          output.writeInt32(3, verNumber_);
        }
        if (!getVersionBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, version_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getPackageNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, packageName_);
        }
        if (!getAppNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appName_);
        }
        if (verNumber_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, verNumber_);
        }
        if (!getVersionBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, version_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage)) {
          return super.equals(obj);
        }
        Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage other = (Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage) obj;

        boolean result = true;
        result = result && getPackageName()
            .equals(other.getPackageName());
        result = result && getAppName()
            .equals(other.getAppName());
        result = result && (getVerNumber()
            == other.getVerNumber());
        result = result && getVersion()
            .equals(other.getVersion());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + PACKAGENAME_FIELD_NUMBER;
        hash = (53 * hash) + getPackageName().hashCode();
        hash = (37 * hash) + APPNAME_FIELD_NUMBER;
        hash = (53 * hash) + getAppName().hashCode();
        hash = (37 * hash) + VERNUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getVerNumber();
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage)
          Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_DeviceAppInfoMessage_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_DeviceAppInfoMessage_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.class, Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.Builder.class);
        }

        // Construct using Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          packageName_ = "";

          appName_ = "";

          verNumber_ = 0;

          version_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_DeviceAppInfoMessage_descriptor;
        }

        public Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage getDefaultInstanceForType() {
          return Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.getDefaultInstance();
        }

        public Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage build() {
          Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage buildPartial() {
          Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage result = new Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage(this);
          result.packageName_ = packageName_;
          result.appName_ = appName_;
          result.verNumber_ = verNumber_;
          result.version_ = version_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage) {
            return mergeFrom((Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage other) {
          if (other == Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.getDefaultInstance()) return this;
          if (!other.getPackageName().isEmpty()) {
            packageName_ = other.packageName_;
            onChanged();
          }
          if (!other.getAppName().isEmpty()) {
            appName_ = other.appName_;
            onChanged();
          }
          if (other.getVerNumber() != 0) {
            setVerNumber(other.getVerNumber());
          }
          if (!other.getVersion().isEmpty()) {
            version_ = other.version_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object packageName_ = "";
        /**
         * <code>string PackageName = 1;</code>
         */
        public java.lang.String getPackageName() {
          java.lang.Object ref = packageName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            packageName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string PackageName = 1;</code>
         */
        public com.google.protobuf.ByteString
            getPackageNameBytes() {
          java.lang.Object ref = packageName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            packageName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string PackageName = 1;</code>
         */
        public Builder setPackageName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          packageName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string PackageName = 1;</code>
         */
        public Builder clearPackageName() {
          
          packageName_ = getDefaultInstance().getPackageName();
          onChanged();
          return this;
        }
        /**
         * <code>string PackageName = 1;</code>
         */
        public Builder setPackageNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          packageName_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object appName_ = "";
        /**
         * <code>string AppName = 2;</code>
         */
        public java.lang.String getAppName() {
          java.lang.Object ref = appName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            appName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string AppName = 2;</code>
         */
        public com.google.protobuf.ByteString
            getAppNameBytes() {
          java.lang.Object ref = appName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            appName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string AppName = 2;</code>
         */
        public Builder setAppName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          appName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string AppName = 2;</code>
         */
        public Builder clearAppName() {
          
          appName_ = getDefaultInstance().getAppName();
          onChanged();
          return this;
        }
        /**
         * <code>string AppName = 2;</code>
         */
        public Builder setAppNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          appName_ = value;
          onChanged();
          return this;
        }

        private int verNumber_ ;
        /**
         * <code>int32 VerNumber = 3;</code>
         */
        public int getVerNumber() {
          return verNumber_;
        }
        /**
         * <code>int32 VerNumber = 3;</code>
         */
        public Builder setVerNumber(int value) {
          
          verNumber_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 VerNumber = 3;</code>
         */
        public Builder clearVerNumber() {
          
          verNumber_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object version_ = "";
        /**
         * <code>string Version = 4;</code>
         */
        public java.lang.String getVersion() {
          java.lang.Object ref = version_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            version_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string Version = 4;</code>
         */
        public com.google.protobuf.ByteString
            getVersionBytes() {
          java.lang.Object ref = version_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            version_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string Version = 4;</code>
         */
        public Builder setVersion(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          version_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string Version = 4;</code>
         */
        public Builder clearVersion() {
          
          version_ = getDefaultInstance().getVersion();
          onChanged();
          return this;
        }
        /**
         * <code>string Version = 4;</code>
         */
        public Builder setVersionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          version_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage)
      }

      // @@protoc_insertion_point(class_scope:Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage)
      private static final Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage();
      }

      public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<DeviceAppInfoMessage>
          PARSER = new com.google.protobuf.AbstractParser<DeviceAppInfoMessage>() {
        public DeviceAppInfoMessage parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DeviceAppInfoMessage(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<DeviceAppInfoMessage> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<DeviceAppInfoMessage> getParserForType() {
        return PARSER;
      }

      public Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int PHONEBRAND_FIELD_NUMBER = 1;
    private volatile java.lang.Object phoneBrand_;
    /**
     * <pre>
     * 手机品牌
     * </pre>
     *
     * <code>string PhoneBrand = 1;</code>
     */
    public java.lang.String getPhoneBrand() {
      java.lang.Object ref = phoneBrand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneBrand_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 手机品牌
     * </pre>
     *
     * <code>string PhoneBrand = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBrandBytes() {
      java.lang.Object ref = phoneBrand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneBrand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONEMODEL_FIELD_NUMBER = 2;
    private volatile java.lang.Object phoneModel_;
    /**
     * <pre>
     * 手机型号
     * </pre>
     *
     * <code>string PhoneModel = 2;</code>
     */
    public java.lang.String getPhoneModel() {
      java.lang.Object ref = phoneModel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneModel_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 手机型号
     * </pre>
     *
     * <code>string PhoneModel = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneModelBytes() {
      java.lang.Object ref = phoneModel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OSVERNUMBER_FIELD_NUMBER = 3;
    private int oSVerNumber_;
    /**
     * <code>int32 OSVerNumber = 3;</code>
     */
    public int getOSVerNumber() {
      return oSVerNumber_;
    }

    public static final int APPINFOS_FIELD_NUMBER = 4;
    private java.util.List<Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage> appInfos_;
    /**
     * <pre>
     * App信息
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
     */
    public java.util.List<Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage> getAppInfosList() {
      return appInfos_;
    }
    /**
     * <pre>
     * App信息
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
     */
    public java.util.List<? extends Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessageOrBuilder> 
        getAppInfosOrBuilderList() {
      return appInfos_;
    }
    /**
     * <pre>
     * App信息
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
     */
    public int getAppInfosCount() {
      return appInfos_.size();
    }
    /**
     * <pre>
     * App信息
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
     */
    public Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage getAppInfos(int index) {
      return appInfos_.get(index);
    }
    /**
     * <pre>
     * App信息
     * </pre>
     *
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
     */
    public Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessageOrBuilder getAppInfosOrBuilder(
        int index) {
      return appInfos_.get(index);
    }

    public static final int NETTYPE_FIELD_NUMBER = 5;
    private volatile java.lang.Object netType_;
    /**
     * <code>string NetType = 5;</code>
     */
    public java.lang.String getNetType() {
      java.lang.Object ref = netType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        netType_ = s;
        return s;
      }
    }
    /**
     * <code>string NetType = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNetTypeBytes() {
      java.lang.Object ref = netType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        netType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPhoneBrandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, phoneBrand_);
      }
      if (!getPhoneModelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, phoneModel_);
      }
      if (oSVerNumber_ != 0) {
        output.writeInt32(3, oSVerNumber_);
      }
      for (int i = 0; i < appInfos_.size(); i++) {
        output.writeMessage(4, appInfos_.get(i));
      }
      if (!getNetTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, netType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPhoneBrandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, phoneBrand_);
      }
      if (!getPhoneModelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, phoneModel_);
      }
      if (oSVerNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, oSVerNumber_);
      }
      for (int i = 0; i < appInfos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, appInfos_.get(i));
      }
      if (!getNetTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, netType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage)) {
        return super.equals(obj);
      }
      Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage other = (Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage) obj;

      boolean result = true;
      result = result && getPhoneBrand()
          .equals(other.getPhoneBrand());
      result = result && getPhoneModel()
          .equals(other.getPhoneModel());
      result = result && (getOSVerNumber()
          == other.getOSVerNumber());
      result = result && getAppInfosList()
          .equals(other.getAppInfosList());
      result = result && getNetType()
          .equals(other.getNetType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PHONEBRAND_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneBrand().hashCode();
      hash = (37 * hash) + PHONEMODEL_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneModel().hashCode();
      hash = (37 * hash) + OSVERNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getOSVerNumber();
      if (getAppInfosCount() > 0) {
        hash = (37 * hash) + APPINFOS_FIELD_NUMBER;
        hash = (53 * hash) + getAppInfosList().hashCode();
      }
      hash = (37 * hash) + NETTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getNetType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage)
        Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.class, Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.Builder.class);
      }

      // Construct using Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAppInfosFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        phoneBrand_ = "";

        phoneModel_ = "";

        oSVerNumber_ = 0;

        if (appInfosBuilder_ == null) {
          appInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          appInfosBuilder_.clear();
        }
        netType_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_descriptor;
      }

      public Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage getDefaultInstanceForType() {
        return Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.getDefaultInstance();
      }

      public Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage build() {
        Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage buildPartial() {
        Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage result = new Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.phoneBrand_ = phoneBrand_;
        result.phoneModel_ = phoneModel_;
        result.oSVerNumber_ = oSVerNumber_;
        if (appInfosBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            appInfos_ = java.util.Collections.unmodifiableList(appInfos_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.appInfos_ = appInfos_;
        } else {
          result.appInfos_ = appInfosBuilder_.build();
        }
        result.netType_ = netType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage) {
          return mergeFrom((Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage other) {
        if (other == Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.getDefaultInstance()) return this;
        if (!other.getPhoneBrand().isEmpty()) {
          phoneBrand_ = other.phoneBrand_;
          onChanged();
        }
        if (!other.getPhoneModel().isEmpty()) {
          phoneModel_ = other.phoneModel_;
          onChanged();
        }
        if (other.getOSVerNumber() != 0) {
          setOSVerNumber(other.getOSVerNumber());
        }
        if (appInfosBuilder_ == null) {
          if (!other.appInfos_.isEmpty()) {
            if (appInfos_.isEmpty()) {
              appInfos_ = other.appInfos_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureAppInfosIsMutable();
              appInfos_.addAll(other.appInfos_);
            }
            onChanged();
          }
        } else {
          if (!other.appInfos_.isEmpty()) {
            if (appInfosBuilder_.isEmpty()) {
              appInfosBuilder_.dispose();
              appInfosBuilder_ = null;
              appInfos_ = other.appInfos_;
              bitField0_ = (bitField0_ & ~0x00000008);
              appInfosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAppInfosFieldBuilder() : null;
            } else {
              appInfosBuilder_.addAllMessages(other.appInfos_);
            }
          }
        }
        if (!other.getNetType().isEmpty()) {
          netType_ = other.netType_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object phoneBrand_ = "";
      /**
       * <pre>
       * 手机品牌
       * </pre>
       *
       * <code>string PhoneBrand = 1;</code>
       */
      public java.lang.String getPhoneBrand() {
        java.lang.Object ref = phoneBrand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneBrand_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 手机品牌
       * </pre>
       *
       * <code>string PhoneBrand = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBrandBytes() {
        java.lang.Object ref = phoneBrand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneBrand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 手机品牌
       * </pre>
       *
       * <code>string PhoneBrand = 1;</code>
       */
      public Builder setPhoneBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneBrand_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 手机品牌
       * </pre>
       *
       * <code>string PhoneBrand = 1;</code>
       */
      public Builder clearPhoneBrand() {
        
        phoneBrand_ = getDefaultInstance().getPhoneBrand();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 手机品牌
       * </pre>
       *
       * <code>string PhoneBrand = 1;</code>
       */
      public Builder setPhoneBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneBrand_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phoneModel_ = "";
      /**
       * <pre>
       * 手机型号
       * </pre>
       *
       * <code>string PhoneModel = 2;</code>
       */
      public java.lang.String getPhoneModel() {
        java.lang.Object ref = phoneModel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneModel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 手机型号
       * </pre>
       *
       * <code>string PhoneModel = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneModelBytes() {
        java.lang.Object ref = phoneModel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneModel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 手机型号
       * </pre>
       *
       * <code>string PhoneModel = 2;</code>
       */
      public Builder setPhoneModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneModel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 手机型号
       * </pre>
       *
       * <code>string PhoneModel = 2;</code>
       */
      public Builder clearPhoneModel() {
        
        phoneModel_ = getDefaultInstance().getPhoneModel();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 手机型号
       * </pre>
       *
       * <code>string PhoneModel = 2;</code>
       */
      public Builder setPhoneModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneModel_ = value;
        onChanged();
        return this;
      }

      private int oSVerNumber_ ;
      /**
       * <code>int32 OSVerNumber = 3;</code>
       */
      public int getOSVerNumber() {
        return oSVerNumber_;
      }
      /**
       * <code>int32 OSVerNumber = 3;</code>
       */
      public Builder setOSVerNumber(int value) {
        
        oSVerNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 OSVerNumber = 3;</code>
       */
      public Builder clearOSVerNumber() {
        
        oSVerNumber_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage> appInfos_ =
        java.util.Collections.emptyList();
      private void ensureAppInfosIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          appInfos_ = new java.util.ArrayList<Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage>(appInfos_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage, Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.Builder, Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessageOrBuilder> appInfosBuilder_;

      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public java.util.List<Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage> getAppInfosList() {
        if (appInfosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(appInfos_);
        } else {
          return appInfosBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public int getAppInfosCount() {
        if (appInfosBuilder_ == null) {
          return appInfos_.size();
        } else {
          return appInfosBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage getAppInfos(int index) {
        if (appInfosBuilder_ == null) {
          return appInfos_.get(index);
        } else {
          return appInfosBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public Builder setAppInfos(
          int index, Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage value) {
        if (appInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppInfosIsMutable();
          appInfos_.set(index, value);
          onChanged();
        } else {
          appInfosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public Builder setAppInfos(
          int index, Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.Builder builderForValue) {
        if (appInfosBuilder_ == null) {
          ensureAppInfosIsMutable();
          appInfos_.set(index, builderForValue.build());
          onChanged();
        } else {
          appInfosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public Builder addAppInfos(Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage value) {
        if (appInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppInfosIsMutable();
          appInfos_.add(value);
          onChanged();
        } else {
          appInfosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public Builder addAppInfos(
          int index, Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage value) {
        if (appInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppInfosIsMutable();
          appInfos_.add(index, value);
          onChanged();
        } else {
          appInfosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public Builder addAppInfos(
          Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.Builder builderForValue) {
        if (appInfosBuilder_ == null) {
          ensureAppInfosIsMutable();
          appInfos_.add(builderForValue.build());
          onChanged();
        } else {
          appInfosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public Builder addAppInfos(
          int index, Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.Builder builderForValue) {
        if (appInfosBuilder_ == null) {
          ensureAppInfosIsMutable();
          appInfos_.add(index, builderForValue.build());
          onChanged();
        } else {
          appInfosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public Builder addAllAppInfos(
          java.lang.Iterable<? extends Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage> values) {
        if (appInfosBuilder_ == null) {
          ensureAppInfosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, appInfos_);
          onChanged();
        } else {
          appInfosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public Builder clearAppInfos() {
        if (appInfosBuilder_ == null) {
          appInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          appInfosBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public Builder removeAppInfos(int index) {
        if (appInfosBuilder_ == null) {
          ensureAppInfosIsMutable();
          appInfos_.remove(index);
          onChanged();
        } else {
          appInfosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.Builder getAppInfosBuilder(
          int index) {
        return getAppInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessageOrBuilder getAppInfosOrBuilder(
          int index) {
        if (appInfosBuilder_ == null) {
          return appInfos_.get(index);  } else {
          return appInfosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public java.util.List<? extends Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessageOrBuilder> 
           getAppInfosOrBuilderList() {
        if (appInfosBuilder_ != null) {
          return appInfosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(appInfos_);
        }
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.Builder addAppInfosBuilder() {
        return getAppInfosFieldBuilder().addBuilder(
            Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.getDefaultInstance());
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.Builder addAppInfosBuilder(
          int index) {
        return getAppInfosFieldBuilder().addBuilder(
            index, Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.getDefaultInstance());
      }
      /**
       * <pre>
       * App信息
       * </pre>
       *
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage AppInfos = 4;</code>
       */
      public java.util.List<Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.Builder> 
           getAppInfosBuilderList() {
        return getAppInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage, Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.Builder, Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessageOrBuilder> 
          getAppInfosFieldBuilder() {
        if (appInfosBuilder_ == null) {
          appInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage, Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage.Builder, Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage.DeviceAppInfoMessageOrBuilder>(
                  appInfos_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          appInfos_ = null;
        }
        return appInfosBuilder_;
      }

      private java.lang.Object netType_ = "";
      /**
       * <code>string NetType = 5;</code>
       */
      public java.lang.String getNetType() {
        java.lang.Object ref = netType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          netType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string NetType = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNetTypeBytes() {
        java.lang.Object ref = netType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          netType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string NetType = 5;</code>
       */
      public Builder setNetType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        netType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string NetType = 5;</code>
       */
      public Builder clearNetType() {
        
        netType_ = getDefaultInstance().getNetType();
        onChanged();
        return this;
      }
      /**
       * <code>string NetType = 5;</code>
       */
      public Builder setNetTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        netType_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage)
    }

    // @@protoc_insertion_point(class_scope:Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNoticeMessage)
    private static final Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage();
    }

    public static Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PostDeviceInfoNoticeMessage>
        PARSER = new com.google.protobuf.AbstractParser<PostDeviceInfoNoticeMessage>() {
      public PostDeviceInfoNoticeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PostDeviceInfoNoticeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PostDeviceInfoNoticeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PostDeviceInfoNoticeMessage> getParserForType() {
      return PARSER;
    }

    public Jubo.JuLiao.IM.Wx.Proto.PostDeviceInfoNotice.PostDeviceInfoNoticeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_DeviceAppInfoMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_DeviceAppInfoMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032PostDeviceInfoNotice.proto\022\027Jubo.JuLia" +
      "o.IM.Wx.Proto\"\252\002\n\033PostDeviceInfoNoticeMe" +
      "ssage\022\022\n\nPhoneBrand\030\001 \001(\t\022\022\n\nPhoneModel\030" +
      "\002 \001(\t\022\023\n\013OSVerNumber\030\003 \001(\005\022[\n\010AppInfos\030\004" +
      " \003(\0132I.Jubo.JuLiao.IM.Wx.Proto.PostDevic" +
      "eInfoNoticeMessage.DeviceAppInfoMessage\022" +
      "\017\n\007NetType\030\005 \001(\t\032`\n\024DeviceAppInfoMessage" +
      "\022\023\n\013PackageName\030\001 \001(\t\022\017\n\007AppName\030\002 \001(\t\022\021" +
      "\n\tVerNumber\030\003 \001(\005\022\017\n\007Version\030\004 \001(\tb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_descriptor,
        new java.lang.String[] { "PhoneBrand", "PhoneModel", "OSVerNumber", "AppInfos", "NetType", });
    internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_DeviceAppInfoMessage_descriptor =
      internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_descriptor.getNestedTypes().get(0);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_DeviceAppInfoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Jubo_JuLiao_IM_Wx_Proto_PostDeviceInfoNoticeMessage_DeviceAppInfoMessage_descriptor,
        new java.lang.String[] { "PackageName", "AppName", "VerNumber", "Version", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
