// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TaskResultNotice.proto

package Jubo.JuLiao.IM.Wx.Proto;

public final class TaskResultNotice {
  private TaskResultNotice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TaskResultNoticeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Jubo.JuLiao.IM.Wx.Proto.TaskResultNoticeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 是否成功
     * </pre>
     *
     * <code>bool Success = 1;</code>
     */
    boolean getSuccess();

    /**
     * <pre>
     * 错误码 Success = true 忽略
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
     */
    int getCodeValue();
    /**
     * <pre>
     * 错误码 Success = true 忽略
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
     */
    Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumErrorCode getCode();

    /**
     * <pre>
     * 错误内容描述 Success = true 忽略
     * </pre>
     *
     * <code>string ErrMsg = 3;</code>
     */
    java.lang.String getErrMsg();
    /**
     * <pre>
     * 错误内容描述 Success = true 忽略
     * </pre>
     *
     * <code>string ErrMsg = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();

    /**
     * <pre>
     * 业务的id,通用的。
     * </pre>
     *
     * <code>int64 TaskId = 4;</code>
     */
    long getTaskId();

    /**
     * <pre>
     *原来执行的任务的类型
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumMsgType TaskType = 5;</code>
     */
    int getTaskTypeValue();
    /**
     * <pre>
     *原来执行的任务的类型
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumMsgType TaskType = 5;</code>
     */
    Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumMsgType getTaskType();

    /**
     * <pre>
     * 执行的微信
     * </pre>
     *
     * <code>string WeChatId = 6;</code>
     */
    java.lang.String getWeChatId();
    /**
     * <pre>
     * 执行的微信
     * </pre>
     *
     * <code>string WeChatId = 6;</code>
     */
    com.google.protobuf.ByteString
        getWeChatIdBytes();
  }
  /**
   * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.TaskResultNoticeMessage}
   */
  public  static final class TaskResultNoticeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Jubo.JuLiao.IM.Wx.Proto.TaskResultNoticeMessage)
      TaskResultNoticeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaskResultNoticeMessage.newBuilder() to construct.
    private TaskResultNoticeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskResultNoticeMessage() {
      success_ = false;
      code_ = 0;
      errMsg_ = "";
      taskId_ = 0L;
      taskType_ = 0;
      weChatId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaskResultNoticeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              code_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              errMsg_ = s;
              break;
            }
            case 32: {

              taskId_ = input.readInt64();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              taskType_ = rawValue;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              weChatId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_TaskResultNoticeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_TaskResultNoticeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage.class, Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <pre>
     * 是否成功
     * </pre>
     *
     * <code>bool Success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <pre>
     * 错误码 Success = true 忽略
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
     */
    public int getCodeValue() {
      return code_;
    }
    /**
     * <pre>
     * 错误码 Success = true 忽略
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
     */
    public Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumErrorCode getCode() {
      Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumErrorCode result = Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumErrorCode.valueOf(code_);
      return result == null ? Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumErrorCode.UNRECOGNIZED : result;
    }

    public static final int ERRMSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object errMsg_;
    /**
     * <pre>
     * 错误内容描述 Success = true 忽略
     * </pre>
     *
     * <code>string ErrMsg = 3;</code>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errMsg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 错误内容描述 Success = true 忽略
     * </pre>
     *
     * <code>string ErrMsg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKID_FIELD_NUMBER = 4;
    private long taskId_;
    /**
     * <pre>
     * 业务的id,通用的。
     * </pre>
     *
     * <code>int64 TaskId = 4;</code>
     */
    public long getTaskId() {
      return taskId_;
    }

    public static final int TASKTYPE_FIELD_NUMBER = 5;
    private int taskType_;
    /**
     * <pre>
     *原来执行的任务的类型
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumMsgType TaskType = 5;</code>
     */
    public int getTaskTypeValue() {
      return taskType_;
    }
    /**
     * <pre>
     *原来执行的任务的类型
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumMsgType TaskType = 5;</code>
     */
    public Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumMsgType getTaskType() {
      Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumMsgType result = Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumMsgType.valueOf(taskType_);
      return result == null ? Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumMsgType.UNRECOGNIZED : result;
    }

    public static final int WECHATID_FIELD_NUMBER = 6;
    private volatile java.lang.Object weChatId_;
    /**
     * <pre>
     * 执行的微信
     * </pre>
     *
     * <code>string WeChatId = 6;</code>
     */
    public java.lang.String getWeChatId() {
      java.lang.Object ref = weChatId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weChatId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 执行的微信
     * </pre>
     *
     * <code>string WeChatId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getWeChatIdBytes() {
      java.lang.Object ref = weChatId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weChatId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (code_ != Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumErrorCode.Success.getNumber()) {
        output.writeEnum(2, code_);
      }
      if (!getErrMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errMsg_);
      }
      if (taskId_ != 0L) {
        output.writeInt64(4, taskId_);
      }
      if (taskType_ != Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumMsgType.UnknownMsg.getNumber()) {
        output.writeEnum(5, taskType_);
      }
      if (!getWeChatIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, weChatId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (code_ != Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumErrorCode.Success.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, code_);
      }
      if (!getErrMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errMsg_);
      }
      if (taskId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, taskId_);
      }
      if (taskType_ != Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumMsgType.UnknownMsg.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, taskType_);
      }
      if (!getWeChatIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, weChatId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage)) {
        return super.equals(obj);
      }
      Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage other = (Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && code_ == other.code_;
      result = result && getErrMsg()
          .equals(other.getErrMsg());
      result = result && (getTaskId()
          == other.getTaskId());
      result = result && taskType_ == other.taskType_;
      result = result && getWeChatId()
          .equals(other.getWeChatId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + code_;
      hash = (37 * hash) + ERRMSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrMsg().hashCode();
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTaskId());
      hash = (37 * hash) + TASKTYPE_FIELD_NUMBER;
      hash = (53 * hash) + taskType_;
      hash = (37 * hash) + WECHATID_FIELD_NUMBER;
      hash = (53 * hash) + getWeChatId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.TaskResultNoticeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Jubo.JuLiao.IM.Wx.Proto.TaskResultNoticeMessage)
        Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_TaskResultNoticeMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_TaskResultNoticeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage.class, Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage.Builder.class);
      }

      // Construct using Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = false;

        code_ = 0;

        errMsg_ = "";

        taskId_ = 0L;

        taskType_ = 0;

        weChatId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_TaskResultNoticeMessage_descriptor;
      }

      public Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage getDefaultInstanceForType() {
        return Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage.getDefaultInstance();
      }

      public Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage build() {
        Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage buildPartial() {
        Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage result = new Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage(this);
        result.success_ = success_;
        result.code_ = code_;
        result.errMsg_ = errMsg_;
        result.taskId_ = taskId_;
        result.taskType_ = taskType_;
        result.weChatId_ = weChatId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage) {
          return mergeFrom((Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage other) {
        if (other == Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.code_ != 0) {
          setCodeValue(other.getCodeValue());
        }
        if (!other.getErrMsg().isEmpty()) {
          errMsg_ = other.errMsg_;
          onChanged();
        }
        if (other.getTaskId() != 0L) {
          setTaskId(other.getTaskId());
        }
        if (other.taskType_ != 0) {
          setTaskTypeValue(other.getTaskTypeValue());
        }
        if (!other.getWeChatId().isEmpty()) {
          weChatId_ = other.weChatId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <pre>
       * 是否成功
       * </pre>
       *
       * <code>bool Success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <pre>
       * 是否成功
       * </pre>
       *
       * <code>bool Success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否成功
       * </pre>
       *
       * <code>bool Success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private int code_ = 0;
      /**
       * <pre>
       * 错误码 Success = true 忽略
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
       */
      public int getCodeValue() {
        return code_;
      }
      /**
       * <pre>
       * 错误码 Success = true 忽略
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
       */
      public Builder setCodeValue(int value) {
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误码 Success = true 忽略
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumErrorCode getCode() {
        Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumErrorCode result = Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumErrorCode.valueOf(code_);
        return result == null ? Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumErrorCode.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 错误码 Success = true 忽略
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
       */
      public Builder setCode(Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        code_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误码 Success = true 忽略
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errMsg_ = "";
      /**
       * <pre>
       * 错误内容描述 Success = true 忽略
       * </pre>
       *
       * <code>string ErrMsg = 3;</code>
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 错误内容描述 Success = true 忽略
       * </pre>
       *
       * <code>string ErrMsg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 错误内容描述 Success = true 忽略
       * </pre>
       *
       * <code>string ErrMsg = 3;</code>
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误内容描述 Success = true 忽略
       * </pre>
       *
       * <code>string ErrMsg = 3;</code>
       */
      public Builder clearErrMsg() {
        
        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误内容描述 Success = true 忽略
       * </pre>
       *
       * <code>string ErrMsg = 3;</code>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errMsg_ = value;
        onChanged();
        return this;
      }

      private long taskId_ ;
      /**
       * <pre>
       * 业务的id,通用的。
       * </pre>
       *
       * <code>int64 TaskId = 4;</code>
       */
      public long getTaskId() {
        return taskId_;
      }
      /**
       * <pre>
       * 业务的id,通用的。
       * </pre>
       *
       * <code>int64 TaskId = 4;</code>
       */
      public Builder setTaskId(long value) {
        
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 业务的id,通用的。
       * </pre>
       *
       * <code>int64 TaskId = 4;</code>
       */
      public Builder clearTaskId() {
        
        taskId_ = 0L;
        onChanged();
        return this;
      }

      private int taskType_ = 0;
      /**
       * <pre>
       *原来执行的任务的类型
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumMsgType TaskType = 5;</code>
       */
      public int getTaskTypeValue() {
        return taskType_;
      }
      /**
       * <pre>
       *原来执行的任务的类型
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumMsgType TaskType = 5;</code>
       */
      public Builder setTaskTypeValue(int value) {
        taskType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *原来执行的任务的类型
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumMsgType TaskType = 5;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumMsgType getTaskType() {
        Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumMsgType result = Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumMsgType.valueOf(taskType_);
        return result == null ? Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumMsgType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *原来执行的任务的类型
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumMsgType TaskType = 5;</code>
       */
      public Builder setTaskType(Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumMsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        taskType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *原来执行的任务的类型
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumMsgType TaskType = 5;</code>
       */
      public Builder clearTaskType() {
        
        taskType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object weChatId_ = "";
      /**
       * <pre>
       * 执行的微信
       * </pre>
       *
       * <code>string WeChatId = 6;</code>
       */
      public java.lang.String getWeChatId() {
        java.lang.Object ref = weChatId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          weChatId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 执行的微信
       * </pre>
       *
       * <code>string WeChatId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getWeChatIdBytes() {
        java.lang.Object ref = weChatId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          weChatId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 执行的微信
       * </pre>
       *
       * <code>string WeChatId = 6;</code>
       */
      public Builder setWeChatId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        weChatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 执行的微信
       * </pre>
       *
       * <code>string WeChatId = 6;</code>
       */
      public Builder clearWeChatId() {
        
        weChatId_ = getDefaultInstance().getWeChatId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 执行的微信
       * </pre>
       *
       * <code>string WeChatId = 6;</code>
       */
      public Builder setWeChatIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        weChatId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Jubo.JuLiao.IM.Wx.Proto.TaskResultNoticeMessage)
    }

    // @@protoc_insertion_point(class_scope:Jubo.JuLiao.IM.Wx.Proto.TaskResultNoticeMessage)
    private static final Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage();
    }

    public static Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaskResultNoticeMessage>
        PARSER = new com.google.protobuf.AbstractParser<TaskResultNoticeMessage>() {
      public TaskResultNoticeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskResultNoticeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TaskResultNoticeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaskResultNoticeMessage> getParserForType() {
      return PARSER;
    }

    public Jubo.JuLiao.IM.Wx.Proto.TaskResultNotice.TaskResultNoticeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Jubo_JuLiao_IM_Wx_Proto_TaskResultNoticeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Jubo_JuLiao_IM_Wx_Proto_TaskResultNoticeMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026TaskResultNotice.proto\022\027Jubo.JuLiao.IM" +
      ".Wx.Proto\032\026TransportMessage.proto\"\312\001\n\027Ta" +
      "skResultNoticeMessage\022\017\n\007Success\030\001 \001(\010\0224" +
      "\n\004Code\030\002 \001(\0162&.Jubo.JuLiao.IM.Wx.Proto.E" +
      "numErrorCode\022\016\n\006ErrMsg\030\003 \001(\t\022\016\n\006TaskId\030\004" +
      " \001(\003\0226\n\010TaskType\030\005 \001(\0162$.Jubo.JuLiao.IM." +
      "Wx.Proto.EnumMsgType\022\020\n\010WeChatId\030\006 \001(\tb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_TaskResultNoticeMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_TaskResultNoticeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Jubo_JuLiao_IM_Wx_Proto_TaskResultNoticeMessage_descriptor,
        new java.lang.String[] { "Success", "Code", "ErrMsg", "TaskId", "TaskType", "WeChatId", });
    Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
